### ISSUE TITLE
Html-based help fails to work

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-packages/sonata#20]
If you load a GAP session, SetHelpViewer("browser"), and ask for Sonata help (e.g. "? sonata ideals and factors"), then it displays help in the terminal window.

The issue seems to be that GAP expects the html manuals to be in pkg/sonata-2.9.1/doc/htm, while Sonata actually has them in pkg/sonata-2.9.1/htm .  One fix is to put a link from the former to the latter.

**Comment by alex-konovalov** [comment]
This is handled in https://github.com/gap-packages/sonata/blob/master/PackageInfo.g 
```
PackageDoc := [
  rec(
  BookName  := "SONATA",
  ArchiveURLSubset := ["doc/ref","htm/ref"],
  HTMLStart := "htm/ref/chapters.htm",
  PDFFile   := "doc/ref/manual.pdf",
  SixFile   := "doc/ref/manual.six",
  LongTitle := "System of nearrings and their applications",
  Autoload  := true
  ),
  rec(
  BookName  := "SONATA Tutorial",
  ArchiveURLSubset := ["doc/tut","htm/tut"],
  HTMLStart := "htm/tut/chapters.htm",
  PDFFile   := "doc/tut/manual.pdf",
  SixFile   := "doc/tut/manual.six",
  LongTitle := "Eight easy pieces for SONATA: a SONATA tutorial",
  Autoload  := false
  ),
],
```
namely in `HTMLStart` components. It's not obvious to me what goes wrong - those point to `htm` and not `doc/htm`. Do the `htm/tut/chapters.htm` and `htm/ref/chapters.htm` files exist?

**Comment by RussWoodroofe** [comment]
@alex-konovalov, the code in helpdef.gi doesn't look at HTMLStart at all, and I can't see anywhere that the HTMLStart entry is referenced, except that package.gi complains if it is not there.  The code in helpdef.gi is hardcoded to replace doc with htm if it ends with doc, and otherwise to put htm after doc.

**Comment by alex-konovalov** [comment]
Hm... this needs further investigation, but if this only happens for gapmacro-based manuals, may happen that we don't support `SetHelpViewer("browser")` for them any more. I suggest to check this with some package which used release tools but has only one manual book, so no subdirectories in `htm`.

**Comment by RussWoodroofe** [comment]
I haven't checked exhaustively, but I've been giving the help system a pretty good workout over the past week or so.  This is the only problem of this particular sort that I've found.

In particular, it looks like Grape uses release tools and the built-in help system, and its html-based help works fine.

Indeed, Html-based help URLs are available in my GAP 4.11 installation for all topics meeting a search of "?S".  I expect that should probably hit almost all packages.

**Comment by alex-konovalov** [comment]
Yes, and I've checked ModIsom, also gapmacro based, and it's html manuals work fine. 

This SONATA's behaviour also present in GAP 4.11.0.

**Comment by fingolfin** [comment]
`HTMLStart` is used for the GAP website, so we know the start page of package manuals.

I've just submitted PR #24 to overhaul the way the manual is built. It also resolves this issue, which is caused by Sonata being one of the rare packages containing multiple help books, unlike e.g. grape. IMHO this is surprising behavior of GAP. But since it is so rare, and for the old manual format, it is not worth it to address it in GAP.
